README.md
=> overview draft in readme.md

Cargo.lock, Cargo.toml, modules/debits/Cargo.toml, modules/debits/src/lib.rs, modules/debits/src/mock.rs, modules/debits/src/tests.rs, modules/primitives/Cargo.toml, modules/support/Cargo.toml, modules/template/Cargo.toml, runtime/Cargo.toml, runtime/src/lib.rs, src/cli.rs
Depends on https://github.com/laminar-protocol/open-runtime-module-library/pull/44
=> fix substrate

modules/auction_manager/src/lib.rs, modules/auction_manager/src/tests.rs, modules/cdp_engine/src/lib.rs, modules/cdp_engine/src/mock.rs, modules/cdp_engine/src/tests.rs, modules/debits/src/lib.rs, modules/debits/src/mock.rs, modules/debits/src/tests.rs, modules/honzon/src/mock.rs, modules/honzon/src/tests.rs, modules/vaults/src/mock.rs, modules/vaults/src/tests.rs
* replace Trait::Currency bound to MultiCurrencyExtended
* add Trait::GetStableCurrencyId
* fix ci tests
=> update debits module

LICENSE, README.md
=> Add LICENSE file and Increase file FaceValue

Cargo.lock, Cargo.toml, runtime/Cargo.toml, runtime/src/lib.rs, src/chain_spec.rs, src/cli.rs, src/service.rs
Update Substrate & ORML
$1M DOT & XBTC for genesis endowed accounts
change block time to 4s
=> Update Substrate & chain_spec

Cargo.lock, Cargo.toml, src/chain_spec.rs
Those values will be used by polkadot apps
=> add chain_spec properties

Cargo.lock, Cargo.toml, runtime/Cargo.toml, runtime/src/lib.rs, src/main.rs, src/rpc.rs, src/service.rs
=> add runtime rpc extension for service

README.md
Change Medium badge link to Acala Medium Publication.
=> Change the link of Medium badge

runtime/src/lib.rs, src/chain_spec.rs
=> rename Board to GeneralCouncil

modules/accounts/src/lib.rs, modules/accounts/src/mock.rs, modules/accounts/src/tests.rs
=> accounts module update

Cargo.lock, Cargo.toml, runtime/Cargo.toml, runtime/src/lib.rs
=> integrate pallet-recovery to acala runtime

Cargo.lock, runtime/Cargo.toml, runtime/src/lib.rs
=> integrate accounts module to runtime

Cargo.lock, Cargo.toml, modules/cdp_engine/src/lib.rs, modules/cdp_treasury/src/lib.rs, runtime/src/lib.rs, src/chain_spec.rs
=> Make all financial parameters configurable in chain spec

modules/cdp_engine/Cargo.toml, modules/cdp_engine/src/debit_exchange_rate_convertor.rs, modules/cdp_engine/src/lib.rs, modules/cdp_engine/src/mock.rs, modules/cdp_engine/src/tests.rs, modules/cdp_treasury/Cargo.toml, modules/cdp_treasury/src/lib.rs, modules/cdp_treasury/src/tests.rs, modules/emergency_shutdown/src/mock.rs, modules/honzon/src/mock.rs, runtime/src/lib.rs
=> code cleanup

Cargo.lock, modules/airdrop/Cargo.toml, modules/airdrop/src/lib.rs, modules/airdrop/src/mock.rs, modules/airdrop/src/tests.rs, modules/primitives/src/lib.rs, runtime/Cargo.toml, runtime/src/lib.rs
=> add airdrop module to runtime

Cargo.lock, Cargo.toml, runtime/Cargo.toml, runtime/src/lib.rs, runtime/tests/integration_test.rs, src/chain_spec.rs, src/rpc.rs, src/service.rs
=> cargo file cleanup

modules/auction_manager/src/lib.rs, modules/loans/src/lib.rs
Adjust account ref count in some cases to prevent replay attacks for these accounts,  which have collateral in CDP or maybe receive tokens from active auctions but have not enough existence token.
resolve #122
=> adjust account ref count for some cases

Cargo.lock, Cargo.toml, modules/dex/rpc/Cargo.toml, modules/dex/rpc/runtime-api/Cargo.toml, modules/dex/rpc/runtime-api/src/lib.rs, modules/dex/rpc/src/lib.rs, modules/dex/src/lib.rs, modules/dex/src/tests.rs, runtime/Cargo.toml, runtime/src/lib.rs, src/rpc.rs
=> Impl rpc abi for dex

modules/cdp_engine/src/lib.rs, modules/dex/src/lib.rs, modules/support/src/lib.rs
fix #137 
And add check to ensure exchange can be successful before exchange with dex.
=> fix calculation and add check

runtime/src/lib.rs
=> Always check signature

modules/cdp_engine/src/lib.rs
=> fix index out of bounds when initialize OffchainWorkerLock

Cargo.lock, Cargo.toml
=> use jemalloc

modules/cdp_treasury/src/lib.rs, modules/dex/src/lib.rs, modules/dex/src/tests.rs, modules/honzon/src/lib.rs, modules/honzon/src/tests.rs, modules/support/src/lib.rs
=> Add compact annotation

Cargo.toml, modules/accounts/Cargo.toml, modules/airdrop/Cargo.toml, modules/auction_manager/Cargo.toml, modules/cdp_engine/Cargo.toml, modules/cdp_treasury/Cargo.toml, modules/dex/Cargo.toml, modules/dex/rpc/Cargo.toml, modules/dex/rpc/runtime-api/Cargo.toml, modules/emergency_shutdown/Cargo.toml, modules/honzon/Cargo.toml, modules/loans/Cargo.toml, modules/prices/Cargo.toml, modules/primitives/Cargo.toml, modules/support/Cargo.toml, modules/template/Cargo.toml, runtime/Cargo.toml
=> Update SCALE to 1.2.0

modules/accounts/src/lib.rs, modules/accounts/src/mock.rs, modules/accounts/src/tests.rs
fixes issue adding tip doesn't add priority, and some other fee related issues
=> fix tx fee charging and priority

Cargo.lock, Cargo.toml, modules/dex/rpc/src/lib.rs, modules/homa/src/lib.rs, modules/homa_treasury/Cargo.toml, modules/homa_treasury/src/lib.rs, modules/staking_pool/rpc/Cargo.toml, modules/staking_pool/rpc/runtime-api/Cargo.toml, modules/staking_pool/rpc/runtime-api/src/lib.rs, modules/staking_pool/rpc/src/lib.rs, modules/staking_pool/src/lib.rs, modules/staking_pool/src/mock.rs, modules/staking_pool/src/tests.rs, modules/support/src/homa.rs, modules/support/src/lib.rs, runtime/Cargo.toml, runtime/src/lib.rs, src/rpc.rs
=> add homa treasury module

Cargo.lock, Cargo.toml, modules/cdp_engine/src/mock.rs, modules/cdp_treasury/src/lib.rs, modules/cdp_treasury/src/mock.rs, modules/dex/Cargo.toml, modules/dex/src/lib.rs, modules/dex/src/mock.rs, modules/dex/src/tests.rs, modules/support/src/lib.rs, runtime/src/lib.rs, runtime/tests/integration_test.rs, src/chain_spec.rs
=> implement liquidity incentive for dex

Cargo.lock, modules/cdp_engine/src/mock.rs, modules/cdp_treasury/src/mock.rs, modules/dex/Cargo.toml, modules/dex/src/lib.rs, modules/dex/src/mock.rs, modules/dex/src/tests.rs, runtime/src/lib.rs, runtime/tests/integration_test.rs, src/chain_spec.rs
1. do some rename
2. accumulate interest just based on liquidity pool amount
3. issue aUSD to module account when accumulate interest
4. add Calls to update liquidity incentive rate and withdraw available interest
=> update liquidity incentive mechanism

modules/auction_manager/src/lib.rs, modules/auction_manager/src/mock.rs, modules/cdp_engine/src/lib.rs, modules/cdp_engine/src/mock.rs, modules/dex/src/mock.rs, modules/dex/src/tests.rs, modules/emergency_shutdown/src/lib.rs, modules/emergency_shutdown/src/mock.rs, modules/honzon/src/mock.rs, modules/prices/src/lib.rs, modules/prices/src/mock.rs, modules/prices/src/tests.rs, modules/support/src/lib.rs, runtime/src/lib.rs
refactor prices module according to https://github.com/laminar-protocol/open-runtime-module-library/pull/136
and add special feedprice for LiquidCurrency(LDOT)
=> refactor prices module

modules/accounts/src/lib.rs, modules/accounts/src/tests.rs
=> update Option<()> to Option<bool> in runtime storage

Cargo.lock, Cargo.toml, modules/accounts/Cargo.toml, modules/airdrop/Cargo.toml, modules/auction_manager/Cargo.toml, modules/cdp_engine/Cargo.toml, modules/cdp_treasury/Cargo.toml, modules/dex/Cargo.toml, modules/dex/rpc/Cargo.toml, modules/dex/rpc/runtime-api/Cargo.toml, modules/emergency_shutdown/Cargo.toml, modules/homa/Cargo.toml, modules/homa_treasury/Cargo.toml, modules/honzon/Cargo.toml, modules/loans/Cargo.toml, modules/nominees_election/Cargo.toml, modules/polkadot_bridge/Cargo.toml, modules/prices/Cargo.toml, modules/primitives/Cargo.toml, modules/staking_pool/Cargo.toml, modules/staking_pool/rpc/Cargo.toml, modules/staking_pool/rpc/runtime-api/Cargo.toml, modules/support/Cargo.toml, modules/template/Cargo.toml, runtime/Cargo.toml, runtime/src/lib.rs, scripts/docker-hub-publish-dev.sh
bump version and upgrade parity-util-mem
=> Upgrade dep

modules/dex/src/lib.rs, runtime/src/lib.rs
=> stop to issue liquidity incentive reward after shutdown

runtime/tests/integration_test.rs
=> Integrate tests

modules/auction_manager/src/lib.rs, modules/auction_manager/src/tests.rs, modules/cdp_engine/src/lib.rs, modules/cdp_treasury/src/lib.rs, modules/cdp_treasury/src/tests.rs, modules/dex/src/lib.rs, modules/emergency_shutdown/src/lib.rs, modules/loans/src/lib.rs, modules/support/src/lib.rs
do not decrease debit pool/surplus pool directly when create debit auction/surplus auction
=> optimize debit pool in cdp_treasury

Cargo.lock, Cargo.toml
enable `--wasm-execution=Compiled`
=> enable wasmtime

Cargo.lock, runtime/Cargo.toml, runtime/build.rs
this is required to run wasm benchmarking
=> bump wasm builder version

modules/auction_manager/src/lib.rs, modules/cdp_engine/src/lib.rs, modules/cdp_treasury/src/lib.rs, modules/loans/src/lib.rs, modules/staking_pool/src/lib.rs
=> expose DispatchError of some modules

modules/auction_manager/src/lib.rs, modules/auction_manager/src/tests.rs
=> update auction deal events

runtime/src/lib.rs
https://github.com/paritytech/polkadot/pull/1086
=> increase block hash count

runtime/src/benchmarking/mod.rs, runtime/src/benchmarking/tokens.rs, runtime/src/benchmarking/utils.rs, runtime/src/benchmarking/vesting.rs, runtime/src/lib.rs
- Update tokens benchmarking following up existential deposit change.
- Add vesting module benchmarking.
=> Vesting module benchmarking

.github/workflows/test.yml, inspect/src/lib.rs, modules/auction_manager/src/lib.rs, modules/cdp_engine/benchmarking/src/lib.rs, modules/cdp_engine/src/debit_exchange_rate_convertor.rs, modules/cdp_engine/src/lib.rs, modules/cdp_engine/src/tests.rs, modules/dex/rpc/runtime-api/src/lib.rs, modules/dex/src/lib.rs, modules/homa_treasury/src/lib.rs, modules/honzon/benchmarking/src/lib.rs, modules/honzon/src/tests.rs, modules/nominees_election/src/lib.rs, modules/polkadot_bridge/src/lib.rs, modules/prices/src/lib.rs, modules/staking_pool/rpc/runtime-api/src/lib.rs, modules/staking_pool/src/lib.rs, runtime/src/constants.rs, runtime/src/lib.rs, runtime/tests/integration_test.rs, src/chain_spec.rs, src/service.rs, utilities/src/offchain_lock.rs
=> Introduce cargo clippy in CI.

.github/workflows/test.yml
=> GH actions cache.

Cargo.lock, modules/auction_manager/Cargo.toml, modules/auction_manager/benchmarking/src/mock.rs, modules/auction_manager/src/lib.rs, modules/auction_manager/src/mock.rs, modules/auction_manager/src/tests.rs, modules/cdp_treasury/src/lib.rs, modules/support/src/lib.rs, runtime/src/lib.rs
resolve #247 
@xlc  The stablecoin obtained from trading with DEX may still be larger than the target. Should the excess part be returned to auction owner? Or keep it as system surplus.
=> update collateral auctin end handler

Cargo.toml
=> Make dev profile faster by compiling deps with opt-level=3

modules/accounts/src/mock.rs, modules/auction_manager/benchmarking/src/mock.rs, modules/auction_manager/src/mock.rs, modules/cdp_engine/benchmarking/src/mock.rs, modules/cdp_engine/src/mock.rs, modules/cdp_treasury/src/lib.rs, modules/cdp_treasury/src/mock.rs, modules/dex/src/lib.rs, modules/dex/src/mock.rs, modules/emergency_shutdown/benchmarking/src/mock.rs, modules/emergency_shutdown/src/mock.rs, modules/homa_treasury/src/lib.rs, modules/honzon/benchmarking/src/mock.rs, modules/honzon/src/mock.rs, modules/loans/src/lib.rs, modules/loans/src/mock.rs, modules/staking_pool/src/lib.rs, modules/staking_pool/src/mock.rs, runtime/src/lib.rs, src/chain_spec.rs
=> configure all module accounts in Trait

modules/cdp_engine/src/lib.rs, modules/cdp_treasury/src/lib.rs, modules/dex/src/lib.rs, modules/emergency_shutdown/src/lib.rs, modules/prices/src/lib.rs, runtime/src/constants.rs, runtime/src/lib.rs, runtime/tests/integration_test.rs, runtime/tests/weights_test.rs
=> add weights and fees tests for downstream modules

Cargo.lock, modules/accounts/src/lib.rs, modules/auction_manager/src/lib.rs, modules/cdp_engine/src/lib.rs, modules/polkadot_bridge/src/lib.rs, modules/prices/src/lib.rs, modules/staking_pool/src/lib.rs, runtime/src/lib.rs
=> code clean

modules/accounts/src/lib.rs, modules/accounts/src/mock.rs, modules/cdp_engine/src/lib.rs, runtime/src/lib.rs, runtime/tests/integration_test.rs
1. add slippage limit when swap fee or open account deposit with DEX to avoid unreasonable losses.
2. configure Accounts as OnReceived of orml_tokens
3. fix some tests in integrate test
=> Fix accounts

Cargo.lock, resources/mandala-dist.json, resources/mandala.json, runtime/Cargo.toml, runtime/src/lib.rs, src/chain_spec.rs
=> Bench db tracking

modules/cdp_engine/benchmarking/src/lib.rs, modules/cdp_engine/src/lib.rs, modules/cdp_engine/src/tests.rs, modules/cdp_treasury/src/lib.rs, modules/cdp_treasury/src/tests.rs, modules/dex/src/lib.rs, modules/dex/src/tests.rs, modules/emergency_shutdown/benchmarking/src/lib.rs, modules/emergency_shutdown/src/lib.rs, modules/emergency_shutdown/src/tests.rs, modules/honzon/benchmarking/src/lib.rs, modules/honzon/src/tests.rs, modules/prices/src/lib.rs, modules/prices/src/tests.rs, runtime/src/lib.rs
=> config EnsureOrigin by  EnsureOneOf

ecosystem-modules/ren/renvm-bridge/src/lib.rs, ecosystem-modules/ren/renvm-bridge/src/mock.rs, ecosystem-modules/ren/renvm-bridge/src/tests.rs, runtime/src/lib.rs, src/chain_spec.rs
=> config RenBTC to dex and cdp

modules/auction_manager/src/lib.rs
=> fix event description

ecosystem-modules/ren/renvm-bridge/src/lib.rs, modules/airdrop/src/lib.rs, modules/auction_manager/src/lib.rs, modules/cdp_engine/src/lib.rs, modules/cdp_treasury/src/lib.rs, modules/dex/src/lib.rs, modules/emergency_shutdown/src/lib.rs, modules/honzon/src/lib.rs, modules/loans/src/lib.rs, modules/polkadot_bridge/src/lib.rs, modules/prices/src/lib.rs, modules/staking_pool/src/lib.rs
After [PR#6684](https://github.com/paritytech/substrate/pull/6684) has been approved and merged, the description of events should be corrected according to the accepted rule.
Close #315
=> Annotated parameter names for events

modules/accounts/src/lib.rs, modules/accounts/src/tests.rs, modules/emergency_shutdown/src/lib.rs
Mostly typo fixes. Changed `FreeTransferEnabledAccounts` value from `Option<bool>` to `Option<()>`.
=> Update accounts and emergency shutdown module.

modules/dex/src/lib.rs
=> accumulate interest to avoid event spam

modules/auction_manager/src/tests.rs, modules/loans/src/lib.rs, modules/loans/src/tests.rs
=> check account ref in unit tests

modules/accounts/src/lib.rs, modules/accounts/src/tests.rs
close #360  :
After discussing with @shaopengw , we decided to check the account to close has no active reserved:
1. the reserved native token must be lte `NewAccountDeposit`
2. the reserved non-native token must be zero
close #367  :
Although can use `repatriate_reserved` instead of `unreserve` & `transfer`,  an extra transfer is still required to transfer other free balance. unreserve reserved_balance to free_balance firstly, then transfer all free_balance can save this step. 
```
// unreserve all reserved native currency
<T as Trait>::Currency::unreserve(native_currency_id, &who, total_reserved_native);
// transfer all free to recipient
<T as Trait>::Currency::transfer(native_currency_id, &who, &recipient, <T as Trait>::Currency::free_balance(native_currency_id, &who))?;
```
=> check reserved when close account

modules/accounts/src/mock.rs, modules/auction_manager/benchmarking/src/mock.rs, modules/auction_manager/src/mock.rs, modules/cdp_engine/src/mock.rs, modules/cdp_treasury/src/mock.rs, modules/dex/src/mock.rs, modules/emergency_shutdown/src/mock.rs, modules/honzon/src/mock.rs, modules/loans/src/mock.rs, modules/nominees_election/src/mock.rs, modules/staking_pool/src/mock.rs, runtime/dev/src/lib.rs
=> Update orml with weightinfo types.

ecosystem-modules/ren/renvm-bridge/src/lib.rs, ecosystem-modules/ren/renvm-bridge/src/mock.rs, ecosystem-modules/ren/renvm-bridge/src/tests.rs, runtime/dev/src/lib.rs
=> store renvm bridge burn events

Cargo.lock, modules/dex/rpc/Cargo.toml, modules/dex/rpc/src/lib.rs, rpc/Cargo.toml, rpc/src/lib.rs, service/Cargo.toml, service/src/client.rs
Still has problem to deserialize the uncertain types(hex string or integer): #349 , I modify the passing param type from generic `Balance` to `String`, use decimal string to do query.
=> enable dex rpc

Cargo.lock, modules/nft/Cargo.toml, modules/nft/src/lib.rs, modules/nft/src/mock.rs, modules/nft/src/tests.rs, runtime/dev/Cargo.toml, runtime/dev/src/constants.rs, runtime/dev/src/lib.rs, runtime/dev/tests/integration_test.rs
=> Add moule-nft

modules/accounts/src/lib.rs, modules/auction_manager/src/lib.rs, modules/auction_manager/src/tests.rs, modules/cdp_engine/src/debit_exchange_rate_convertor.rs, modules/cdp_engine/src/lib.rs, modules/dex/rpc/runtime-api/src/lib.rs, modules/dex/rpc/src/lib.rs, modules/dex/src/lib.rs, modules/dex/src/tests.rs, modules/incentives/src/mock.rs, modules/prices/src/lib.rs, modules/support/src/lib.rs, runtime/dev/src/lib.rs
Closes #356
Should fix most of the issues except weights, storage RW optimizations, comments, and test coverages.
=> improve & refactor

modules/accounts/src/lib.rs
=> fix transaction priority of ChargeTransactionPayment

Cargo.lock, modules/accounts/Cargo.toml, modules/accounts/src/lib.rs, modules/accounts/src/mock.rs, modules/accounts/src/tests.rs, runtime/dev/src/lib.rs
resolve #448 , and close #289  close #443
=> remove free transfer feature

Cargo.lock, cli/src/command.rs, inspect/src/command.rs, service/Cargo.toml, service/src/client.rs, service/src/lib.rs
=> Subcommand support Karura & Acala

ecosystem-modules/ren/renvm-bridge/src/lib.rs, ecosystem-modules/ren/renvm-bridge/src/tests.rs
cc @qwer951123 this changes `DestAddress` from `[u8; 20]` to `Vec<u8>`
=> update burn DestAddress type

cli/src/command.rs
=> default to mandala runtime

modules/evm/src/runner/native.rs
=> EVM: Call precompile contract in native runner.

modules/cdp_engine/src/lib.rs
=> add more offchain worker logs to indicate iteration consumption

modules/evm-accounts/src/lib.rs, runtime/mandala/src/benchmarking/authority.rs, runtime/mandala/tests/integration_test.rs
=> Update evm account map

Makefile, modules/evm/src/lib.rs, modules/evm/src/runner/native.rs
=> include more information when execution failed

modules/evm/rpc/runtime_api/src/lib.rs, modules/evm/rpc/src/call_request.rs, modules/evm/rpc/src/evm_api.rs, modules/evm/rpc/src/lib.rs, modules/evm/src/lib.rs, modules/evm/src/runner/handler.rs, modules/evm/src/runner/mod.rs, modules/evm/src/runner/native.rs, modules/evm/src/tests.rs, primitives/src/evm.rs, rpc/src/lib.rs, runtime/acala/src/lib.rs, runtime/karura/src/lib.rs, runtime/mandala/src/lib.rs, service/src/client.rs
* Created new file for handler to reduce confusion
* Use balance instead of U256
* Propagate transfer error
* Fix transfer call_stipend which was removed #559
=> EVM refactor

modules/evm-accounts/src/lib.rs, modules/evm-accounts/src/tests.rs, runtime/mandala/src/benchmarking/evm_accounts.rs, runtime/mandala/tests/integration_test.rs
=> Ensure accountId and ethAddress has not been mapped

Cargo.lock, runtime/acala/Cargo.toml, runtime/acala/build.rs, runtime/karura/Cargo.toml, runtime/karura/build.rs, runtime/mandala/Cargo.toml, runtime/mandala/build.rs
=> Update wasm-builder 3.0.0

runtime/acala/src/lib.rs, runtime/karura/src/lib.rs, runtime/mandala/src/lib.rs
=> Set evm chain-id

Cargo.lock, Cargo.toml, Makefile, runtime/mandala/Cargo.toml, runtime/mandala/src/lib.rs
=> Add features with-ethereum-compatibility

modules/evm/src/lib.rs, modules/evm/src/runner/handler.rs, modules/evm/src/runner/native.rs
=> EVM storage refactor

modules/evm/src/lib.rs, modules/evm/src/runner/mod.rs, modules/evm/src/runner/native.rs, modules/evm/src/tests.rs, runtime/acala/src/lib.rs, runtime/karura/src/lib.rs, runtime/mandala/src/lib.rs, service/src/chain_spec/mandala.rs, service/src/chain_spec/mod.rs
=> EVM: deploy system contract

modules/nft/benchmarking/src/mock.rs, modules/nft/src/mock.rs, runtime/acala/src/lib.rs, runtime/common/src/precompile/input.rs, runtime/common/src/precompile/nft.rs, runtime/karura/src/lib.rs, runtime/mandala/src/lib.rs
So it works for https://github.com/AcalaNetwork/Acala/issues/597
cc @ntduan will need to update type definition for acala.js
=> change class id to u32

modules/evm/src/lib.rs, modules/evm/src/runner/handler.rs
=> Update evm config

Cargo.lock, modules/evm-bridge/src/lib.rs, modules/evm/Cargo.toml, modules/evm/rpc/runtime_api/src/lib.rs, modules/evm/rpc/src/lib.rs, modules/evm/src/lib.rs, modules/evm/src/runner/mod.rs, modules/evm/src/runner/native.rs, modules/evm/src/tests.rs, modules/support/src/lib.rs, primitives/Cargo.toml, primitives/src/evm.rs, runtime/acala/src/lib.rs, runtime/karura/src/lib.rs, runtime/mandala/src/lib.rs
=> update evm to 0.19.0

modules/transaction_payment/Cargo.toml, modules/transaction_payment/src/mock.rs
=> Remove unnecessary thread local

.gitignore, modules/evm/src/runner/handler.rs, modules/evm/src/runner/native.rs, runtime/common/src/lib.rs, runtime/common/src/precompile/mod.rs, runtime/common/src/precompile/multicurrency.rs
Add more evm logs and fix contracts calling predeploy
=> Fix call predeploy

Cargo.lock, modules/evm-accounts/Cargo.toml, modules/evm-accounts/src/lib.rs, modules/evm-accounts/src/mock.rs, modules/evm-accounts/src/tests.rs, modules/evm-bridge/src/mock.rs, modules/evm/src/lib.rs, modules/evm/src/mock.rs, modules/evm/src/runner/handler.rs, modules/evm/src/runner/mod.rs, modules/evm/src/tests.rs, primitives/src/evm.rs, primitives/src/lib.rs, primitives/src/mocks.rs, runtime/common/src/precompile/input.rs, runtime/common/src/precompile/nft.rs
so every Substrate account also have a default evm account as well.
=> Update evm account

modules/evm/src/runner/handler.rs, modules/homa/src/default_weight.rs, modules/homa/src/lib.rs, modules/polkadot_bridge/src/lib.rs, modules/staking_pool/src/lib.rs, modules/staking_pool/src/tests.rs, runtime/acala/src/lib.rs, runtime/acala/src/weights/homa.rs, runtime/acala/src/weights/mod.rs, runtime/karura/src/lib.rs, runtime/karura/src/weights/homa.rs, runtime/karura/src/weights/mod.rs, runtime/mandala/src/benchmarking/homa.rs, runtime/mandala/src/benchmarking/mod.rs, runtime/mandala/src/lib.rs, runtime/mandala/src/weights/homa.rs, runtime/mandala/src/weights/mod.rs
=> Merge storages

modules/evm/Cargo.toml, modules/evm/src/lib.rs, modules/evm/src/tests.rs, runtime/mandala/Cargo.toml
=> make contract deployed by default when with-ethereum-compatibility

modules/evm/src/lib.rs, modules/support/src/lib.rs, runtime/common/src/precompile/state_rent.rs
=> Precompile add deployment fee

modules/evm-accounts/src/lib.rs, runtime/common/src/lib.rs, runtime/mandala/src/lib.rs, runtime/mandala/tests/integration_test.rs
=> MultiAddress support Address20

bin/acala-dev/service/src/chain_spec/mandala.rs, bin/acala/service/src/chain_spec/mandala.rs
=> fix duplicated balance issue

modules/currencies/src/mock.rs, modules/evm-bridge/src/mock.rs, modules/evm/src/lib.rs, modules/evm/src/mock.rs, modules/evm/src/runner/handler.rs, modules/evm/src/runner/mod.rs, modules/evm/src/tests.rs, modules/support/src/lib.rs, primitives/src/evm.rs, runtime/acala/src/lib.rs, runtime/common/src/precompile/state_rent.rs, runtime/karura/src/lib.rs, runtime/mandala/src/lib.rs, runtime/mandala/tests/integration_test.rs
=> Remove ContractExistentialDeposit

modules/evm/src/runner/handler.rs, modules/evm/src/runner/mod.rs, modules/evm/src/tests.rs
=> Fix call non-exist contracts

modules/evm/src/runner/handler.rs, modules/evm/src/runner/mod.rs, modules/evm/src/tests.rs
Reverts AcalaNetwork/Acala#672
=> Revert "Fix call non-exist contracts"

modules/currencies/src/mock.rs, modules/evm-bridge/src/mock.rs, modules/evm/src/default_weight.rs, modules/evm/src/lib.rs, modules/evm/src/mock.rs, modules/evm/src/tests.rs, modules/nft/src/lib.rs, modules/nft/src/tests.rs, modules/support/src/lib.rs, runtime/acala/src/lib.rs, runtime/acala/src/weights/evm.rs, runtime/common/src/precompile/state_rent.rs, runtime/karura/src/lib.rs, runtime/karura/src/weights/evm.rs, runtime/mandala/src/benchmarking/evm.rs, runtime/mandala/src/lib.rs, runtime/mandala/src/weights/evm.rs, runtime/mandala/tests/integration_test.rs
=> Update transfer maintainer

Cargo.lock, bin/acala-dev/service/src/chain_spec/mandala.rs, bin/acala/service/Cargo.toml, bin/acala/service/src/chain_spec/acala.rs, bin/acala/service/src/chain_spec/karura.rs, bin/acala/service/src/chain_spec/mandala.rs, ecosystem-modules/ren/renvm-bridge/Cargo.toml, ecosystem-modules/ren/renvm-bridge/src/lib.rs, ecosystem-modules/ren/renvm-bridge/src/mock.rs, ecosystem-modules/ren/renvm-bridge/src/tests.rs, runtime/acala/src/lib.rs, runtime/karura/src/lib.rs, runtime/mandala/src/lib.rs
=> Make RenVmPublicKey upgradable

modules/currencies/src/lib.rs, modules/currencies/src/mock.rs, modules/currencies/src/tests.rs, modules/evm-bridge/src/lib.rs, modules/evm/src/lib.rs, modules/nft/benchmarking/src/mock.rs, modules/nft/src/mock.rs, modules/support/src/lib.rs, modules/transaction_payment/src/mock.rs, runtime/acala/src/lib.rs, runtime/karura/src/lib.rs, runtime/mandala/src/lib.rs
Closes: #677 
There still have a bug, which causes `https://polkadot.js.org` to fail to call the module's Call
=> Add evm SignedExtension

Cargo.lock, Cargo.toml, bin/acala-dev/service/Cargo.toml, bin/acala-dev/service/src/chain_spec/mandala.rs, bin/acala-dev/service/src/client.rs, bin/acala/service/Cargo.toml, bin/acala/service/src/chain_spec/acala.rs, bin/acala/service/src/chain_spec/karura.rs, bin/acala/service/src/chain_spec/mandala.rs, bin/acala/service/src/client.rs, rpc/Cargo.toml, rpc/src/lib.rs, runtime/acala/Cargo.toml, runtime/acala/src/lib.rs, runtime/karura/Cargo.toml, runtime/karura/src/lib.rs, runtime/mandala/Cargo.toml, runtime/mandala/src/lib.rs
=> Remove pallet-contracts.

Cargo.lock, modules/transaction_payment/Cargo.toml, modules/transaction_payment/src/default_weight.rs, modules/transaction_payment/src/lib.rs, modules/transaction_payment/src/mock.rs, modules/transaction_payment/src/tests.rs, runtime/acala/src/weights/transaction_payment.rs, runtime/karura/src/weights/transaction_payment.rs, runtime/mandala/src/weights/transaction_payment.rs
=> Refactor fee charge

Cargo.lock, modules/auction_manager/src/lib.rs, modules/auction_manager/src/mock.rs, modules/auction_manager/src/tests.rs, modules/cdp_engine/src/lib.rs, modules/cdp_engine/src/mock.rs, modules/cdp_engine/src/tests.rs, modules/cdp_treasury/src/lib.rs, modules/cdp_treasury/src/mock.rs, modules/cdp_treasury/src/tests.rs, modules/currencies/src/lib.rs, modules/currencies/src/mock.rs, modules/currencies/src/tests.rs, modules/dex/src/lib.rs, modules/dex/src/mock.rs, modules/dex/src/tests.rs, modules/emergency_shutdown/src/lib.rs, modules/emergency_shutdown/src/mock.rs, modules/evm-accounts/src/lib.rs, modules/evm-accounts/src/tests.rs, modules/evm-bridge/src/lib.rs, modules/evm-bridge/src/mock.rs, modules/evm-bridge/src/tests.rs, modules/evm/src/lib.rs, modules/evm/src/mock.rs, modules/evm/src/tests.rs
Similar to orml changes https://github.com/open-web3-stack/open-runtime-module-library/pull/362
=> Apply pallet macro conventions.

primitives/src/lib.rs
**Description**
Added token symbols into primitives.
=> Added Plasm Network tokens

runtime/common/src/precompile/schedule_call.rs, runtime/common/src/precompile/tests.rs
scheduled_call support dynamic arrays
=> Fix schedule support dynamic arrays

modules/incentives/src/lib.rs
=> Add claim rewards event

modules/evm/rpc/Cargo.toml, modules/evm/rpc/src/call_request.rs, modules/evm/rpc/src/lib.rs, modules/evm/src/mock.rs
=> Improve gas estimation logic

.github/workflows/publish.yml
=> Add action to publish

.github/workflows/publish.yml, scripts/generate-tokens-and-predeploy-contracts.sh
Add build directory into contract package.
=> Add contract build

Cargo.lock, Makefile, bin/acala-dev/cli/src/command.rs, bin/acala-dev/service/src/chain_spec/mandala.rs, bin/acala/service/src/chain_spec/mandala.rs
=> Make mandala the default chain spec

runtime/acala/src/lib.rs, runtime/karura/src/lib.rs, runtime/mandala/src/lib.rs
=> Use native decimal for relay chain tokens.

Cargo.lock, bin/acala-dev/Cargo.lock, runtime/acala/src/lib.rs, runtime/karura/src/lib.rs, runtime/mandala/src/lib.rs
Companion of https://github.com/open-web3-stack/open-runtime-module-library/pull/401
=> Use cumulus xcm-handler to execute XCM locally.

Makefile
`make cargo-update` will do cargo update for all packages. Additionally, `make update` is updated following the new workspace structure.
=> Add 'make cargo-update'

Cargo.lock, Cargo.toml, bin/acala-dev/Cargo.lock, bin/acala-dev/Cargo.toml, bin/acala-dev/cli/Cargo.lock, bin/acala-dev/service/Cargo.lock, bin/acala/Cargo.toml
~Context: https://github.com/paritytech/substrate/issues/8366~
=> Bump dependencies

.github/workflows/publish.yml, Cargo.lock, bin/acala-dev/Cargo.lock, runtime/acala/src/lib.rs, runtime/common/Cargo.toml, runtime/common/src/precompile/mock.rs, runtime/common/src/precompile/oracle.rs, runtime/common/src/precompile/tests.rs, runtime/karura/src/lib.rs, runtime/mandala/src/lib.rs
=> Fix oracle precompiles data source

primitives/src/currency.rs, runtime/common/src/lib.rs, runtime/mandala/src/lib.rs
- Adds the kilt coin to the Mandala Runtime
=> add KILT Coin as NonNativeCurrency

Cargo.lock, bin/acala-dev/Cargo.lock, modules/evm/Cargo.toml, modules/evm/src/precompiles.rs, runtime/common/src/precompile/mod.rs
=> Sha3FIPS standard precompiles and ECDSA public key recovery

primitives/src/currency.rs
Added BCG to supported currencies.
=> Added Bit.Country Token

Cargo.lock, bin/acala-dev/Cargo.lock, modules/evm-accounts/src/lib.rs, modules/evm-accounts/src/mock.rs, modules/transaction-payment/src/lib.rs, runtime/acala/src/lib.rs, runtime/karura/src/lib.rs, runtime/mandala/src/lib.rs
this will ensure there is some provider for evm accounts without reserve, which will prevent user from delete the account by transfer all the funds
=> ensure ExistentialDeposit when claim evm account

bin/acala/cli/src/command.rs
=> Return error if no chain parameter specified.

runtime/acala/src/lib.rs, runtime/karura/src/lib.rs, runtime/mandala/src/lib.rs, runtime/mandala/tests/integration_test.rs
=> Fix currency id convert.

bin/acala-dev/service/src/chain_spec/mandala.rs, bin/acala/service/src/chain_spec/acala.rs, bin/acala/service/src/chain_spec/karura.rs, bin/acala/service/src/chain_spec/mandala.rs, modules/incentives/Cargo.toml, modules/incentives/src/lib.rs, modules/incentives/src/mock.rs, runtime/acala/src/lib.rs, runtime/karura/src/lib.rs, runtime/mandala/src/lib.rs
the native issuing in module-auction-manager will be removed along with debit auction
=> transfer native from unrelease vault account instead of issuing

modules/evm/rpc/src/evm_api.rs, modules/evm/rpc/src/lib.rs, runtime/acala/src/lib.rs, runtime/karura/src/lib.rs, runtime/mandala/src/lib.rs
=> Fix estimate-resource rpc, add caller

modules/evm/rpc/src/evm_api.rs, modules/evm/rpc/src/lib.rs
=> Fix evm rpc use the block argument

modules/evm/src/runner/storage_meter.rs
=> check storage limit on finish

modules/evm-manager/src/lib.rs, modules/evm-manager/src/tests.rs, primitives/src/currency.rs, primitives/src/tests.rs, runtime/common/src/precompile/input.rs, runtime/common/src/precompile/tests.rs
=> update encode/decode currencyId

runtime/acala/Cargo.toml, runtime/karura/Cargo.toml, runtime/mandala/Cargo.toml
=> disable logging for runtime benchmarks

runtime/acala/Cargo.toml, runtime/karura/Cargo.toml, runtime/mandala/Cargo.toml
=> On chain release build

Cargo.lock, bin/acala-dev/Cargo.lock, modules/evm/rpc/Cargo.toml, modules/evm/src/precompiles.rs, modules/homa-validator-list/Cargo.toml, runtime/common/src/precompile/mod.rs
=> Fix evm precompiles

bin/acala/service/src/chain_spec/acala.rs, bin/acala/service/src/chain_spec/karura.rs, bin/acala/service/src/chain_spec/mandala.rs
Replaced all usages in chain specs.
=> Add PARA_ID const.

modules/honzon/Cargo.toml, modules/honzon/src/lib.rs, modules/honzon/src/mock.rs, modules/honzon/src/tests.rs, runtime/acala/src/lib.rs, runtime/karura/src/benchmarking/honzon.rs, runtime/karura/src/lib.rs, runtime/mandala/src/benchmarking/honzon.rs, runtime/mandala/src/lib.rs
=> deposit for honzon authorization

modules/evm/rpc/src/lib.rs
=> Fix evm rpc call.

modules/evm/src/lib.rs, modules/evm/src/runner/handler.rs, modules/evm/src/runner/mod.rs, modules/evm/src/tests.rs
=> check the range of the user's contract address

node/service/src/chain_spec/karura.rs, runtime/acala/src/constants.rs, runtime/acala/src/lib.rs, runtime/common/src/lib.rs, runtime/karura/src/authority.rs, runtime/karura/src/benchmarking/auction_manager.rs, runtime/karura/src/benchmarking/cdp_engine.rs, runtime/karura/src/benchmarking/dex.rs, runtime/karura/src/benchmarking/evm.rs, runtime/karura/src/benchmarking/honzon.rs, runtime/karura/src/constants.rs, runtime/karura/src/lib.rs, runtime/mandala/src/constants.rs, runtime/mandala/src/lib.rs
last minute change on Friday night never goes wrong
closes #876
=> parameter changes

modules/evm/rpc/src/lib.rs
https://github.com/paritytech/frontier/pull/363
=> Fix evm estimate rpc

runtime/acala/src/lib.rs, runtime/karura/src/benchmarking/vesting.rs, runtime/karura/src/lib.rs, runtime/mandala/src/benchmarking/gradually_update.rs, runtime/mandala/src/benchmarking/vesting.rs, runtime/mandala/src/lib.rs
=> Updated runtimes for new vesting and gradually_update

ecosystem-modules/ren/renvm-bridge/src/lib.rs, modules/cdp-treasury/src/lib.rs, modules/cdp-treasury/src/tests.rs, modules/loans/src/lib.rs, modules/loans/src/tests.rs, modules/nft/src/tests.rs, modules/polkadot-bridge/src/lib.rs, modules/staking-pool/src/lib.rs
=> Replace custom arithmetic error

modules/evm/src/lib.rs, modules/evm/src/runner/handler.rs
=> Bounded evm

modules/polkadot-bridge/src/lib.rs, runtime/acala/src/lib.rs, runtime/mandala/src/lib.rs
=> Migrated polkadot-bridge Storage to BoundedVec

.github/workflows/publish.yml, .github/workflows/test.yml, scripts/Dockerfile, scripts/init.sh, scripts/srtool-build.sh
=> Change rustc nightly version.

modules/collator-selection/src/lib.rs, modules/collator-selection/src/tests.rs, runtime/karura/src/benchmarking/collator_selection.rs, runtime/mandala/src/benchmarking/collator_selection.rs
=> Use ValidatorSet::validators to get authors

modules/auction-manager/src/tests.rs, modules/cdp-engine/src/tests.rs, modules/cdp-treasury/src/tests.rs, modules/dex/src/lib.rs, modules/dex/src/tests.rs, modules/incentives/src/mock.rs, modules/prices/src/mock.rs, modules/support/src/lib.rs, modules/transaction-payment/src/tests.rs, runtime/common/src/precompile/dex.rs, runtime/common/src/precompile/tests.rs, runtime/karura/src/benchmarking/cdp_engine.rs, runtime/karura/src/benchmarking/dex.rs, runtime/karura/src/benchmarking/honzon.rs, runtime/mandala/src/benchmarking/cdp_engine.rs, runtime/mandala/src/benchmarking/dex.rs, runtime/mandala/src/benchmarking/honzon.rs, runtime/mandala/tests/integration_test.rs
need to update pre-deployed dex contract to support these params @zjb0807
=> check limit when add/remove liquidity

Cargo.lock, runtime/acala/Cargo.toml, runtime/karura/Cargo.toml, runtime/mandala/Cargo.toml
=> update wasm builder

modules/evm/rpc/runtime_api/src/lib.rs
Closes: #1086 
Tested by https://github.com/AcalaNetwork/evm-examples/pull/26
=> Add skip_initialize_block for call and create

modules/loans/src/lib.rs, modules/loans/src/mock.rs, modules/loans/src/tests.rs, primitives/src/currency.rs, runtime/karura/src/benchmarking/cdp_engine.rs, runtime/karura/src/benchmarking/honzon.rs, runtime/karura/src/benchmarking/incentives.rs, runtime/mandala/src/benchmarking/cdp_engine.rs, runtime/mandala/src/benchmarking/honzon.rs, runtime/mandala/src/benchmarking/incentives.rs
=> Update orml token

.github/workflows/srtool.yml
=> Add srtool and subwasm workflow

Cargo.lock, modules/evm-accounts/src/lib.rs, modules/evm-accounts/src/mock.rs, modules/evm/rpc/runtime_api/Cargo.toml, runtime/acala/src/lib.rs, runtime/karura/src/lib.rs, runtime/mandala/src/lib.rs, runtime/mandala/tests/integration_test.rs
Closes: #859 
https://github.com/open-web3-stack/open-runtime-module-library/blob/32666fd132119cfb0a6299b10909d903b0e9f5c8/tokens/src/lib.rs#L477
Tokens also add system provider.
=> Add evm account integration test

runtime/karura/src/lib.rs
Goals:
- Include bug fixes since genesis
- Enable enough feature to allow us to distribute rewards safely
=> First runtime upgrade for Karura

runtime/karura/src/lib.rs, runtime/mandala/src/constants.rs, runtime/mandala/src/lib.rs
To make it consistent with Karura.
=> Use fixed rate trader for XCM in mandala.

node/service/src/chain_spec/karura.rs
fix general council (updated via sudo)
add ss58Format
=> Update karura chain spec

.github/workflows/verify-bootnotes.yml, Makefile, scripts/verify-bootnodes.sh
=> Add script to verify bootnodes

modules/homa-validator-list/src/lib.rs, modules/homa-validator-list/src/mock.rs, modules/homa-validator-list/src/tests.rs, runtime/acala/src/lib.rs, runtime/mandala/src/lib.rs
=> Update to use to relay chain block number

modules/collator-selection/src/lib.rs, modules/collator-selection/src/mock.rs, runtime/acala/src/lib.rs, runtime/karura/src/benchmarking/collator_selection.rs, runtime/karura/src/lib.rs, runtime/mandala/src/benchmarking/collator_selection.rs, runtime/mandala/src/lib.rs, scripts/verify-bootnodes.sh
=> Improve collator selection

modules/collator-selection/src/lib.rs, modules/transaction-payment/src/mock.rs, modules/transaction-payment/src/tests.rs, runtime/acala/src/lib.rs, runtime/karura/src/benchmarking/collator_selection.rs, runtime/karura/src/lib.rs, runtime/mandala/src/benchmarking/collator_selection.rs, runtime/mandala/src/lib.rs
=> Add tx fee handling

.github/workflows/srtool.yml
=> Fix srtool

Cargo.lock, modules/prices/src/lib.rs, modules/prices/src/tests.rs
=> use uint::integer_sqrt

runtime/karura/src/lib.rs
Enable more governance pallets
Enable collator selection and sessions
Enable vesting so people can claim vested tokens
=> enable more pallets

ecosystem-modules/starport/README.md, ecosystem-modules/starport/src/lib.rs
Added a README documentation for the Starport module
=> README for the starport module

modules/dex/src/lib.rs, modules/dex/src/tests.rs, runtime/karura/src/benchmarking/dex.rs, runtime/mandala/src/benchmarking/dex.rs, runtime/mandala/tests/integration_test.rs
=> Provisioning enhancement

Cargo.lock, runtime/acala/src/lib.rs, runtime/common/Cargo.toml, runtime/common/src/lib.rs, runtime/karura/src/lib.rs, runtime/mandala/src/lib.rs
Moved the code that are shared by Acala, Karura and Mandala into the Common's module
=> Refactored some code common to runtimes

.github/workflows/coverage.yml, .github/workflows/test.yml, README.md
=> add coverage actions

.github/workflows/coverage.yml, .github/workflows/test.yml
=> Rename GH actions.

.codecov.yml, .github/workflows/coverage.yml, .github/workflows/test.yml, Cargo.lock, modules/homa-lite/Cargo.toml, modules/incentives/src/lib.rs, modules/incentives/src/mock.rs, modules/incentives/src/tests.rs, runtime/acala/src/lib.rs, runtime/karura/src/benchmarking/incentives.rs, runtime/karura/src/lib.rs, runtime/mandala/src/benchmarking/incentives.rs, runtime/mandala/src/lib.rs
=> Remove RewardsVaultAccountId

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, scripts/Dockerfile
fixes #1185 
adds devcontainer, took a generic devcontainer template for rust I think the settings look reasonable :palm_tree: 
Edit: I believe CI is complaining about something unrelated to the pr
=> add dev container

modules/transaction-payment/src/lib.rs, modules/transaction-payment/src/tests.rs
=> set fee swap path should prevent starting from native token

primitives/src/currency.rs
=> Update serde rule of some enum which is the param type of rpc to camel case

modules/cdp-engine/Cargo.toml, modules/cdp-engine/src/lib.rs, modules/cdp-engine/src/mock.rs, modules/cdp-engine/src/tests.rs, modules/honzon/src/lib.rs, modules/honzon/src/tests.rs, runtime/mandala/src/benchmarking/honzon.rs
=> set max collateral when close cdp has debit by dex

runtime/acala/src/lib.rs, runtime/common/src/lib.rs, runtime/karura/src/lib.rs, runtime/mandala/src/lib.rs
=> Improve ProxyType

runtime/common/src/lib.rs, runtime/integration-tests/src/integration_tests.rs, runtime/karura/src/constants.rs, runtime/karura/src/lib.rs, runtime/mandala/src/constants.rs, runtime/mandala/src/lib.rs
Unify sub accounts and use enum instead const
Make sure the parachain id in integration test is 2000 to match what we have on Karura.
=> update sub accounts

modules/dex/src/lib.rs, modules/dex/src/tests.rs
close #1337 
@qwer951123 update sdk, front-end, subsql, and ensure them be compatible with the old event.
=> update the event fields of Swap

modules/auction-manager/src/lib.rs, modules/auction-manager/src/mock.rs, modules/auction-manager/src/tests.rs, modules/cdp-engine/src/lib.rs, modules/cdp-engine/src/mock.rs, modules/cdp-engine/src/tests.rs, modules/cdp-treasury/src/lib.rs, modules/cdp-treasury/src/tests.rs, modules/honzon/src/mock.rs, modules/support/src/lib.rs, runtime/acala/src/lib.rs, runtime/karura/src/lib.rs, runtime/mandala/src/lib.rs
=> suport alternative path for some internal swap

Cargo.lock, modules/evm-manager/src/lib.rs, primitives/Cargo.toml, primitives/src/currency.rs, runtime/karura/src/lib.rs, runtime/mandala/src/benchmarking/nutsfinance_stable_asset.rs, runtime/mandala/src/lib.rs
=> stable-asset

modules/currencies/src/lib.rs, modules/currencies/src/tests.rs
=> do not use default when real origin not found

modules/auction-manager/src/lib.rs, modules/cdp-engine/src/lib.rs
companion to https://github.com/open-web3-stack/open-runtime-module-library/pull/600
=> Use frame-support library instead of orml-utilities for Iterators

scripts/Dockerfile
=> remove cargo chef

Makefile, scripts/clean-runtimes.sh
Compiler panics are annoying, script to `cargo clean` is nice
=> Adds make clean-runtimes

node/cli/src/command.rs
Closes #1373
Problem originates upstream in cumulus, this should be a useful work around
=> Purge-chain to work for --dev

runtime/integration-tests/src/integration_tests.rs
=> Integration tests ensuring dust whitelist works as intended

runtime/integration-tests/src/integration_tests.rs
=> proxy integration test

.github/workflows/extrinsic-ordering-check-from-bin.yml, Cargo.lock, node/cli/Cargo.toml
Closes #1410 
Currently is using an edited version of `polkadot-js-tools` https://github.com/ermalkaleci/tools and I've opened a PR to make `metadata-cmp` accept custom types https://github.com/polkadot-js/tools/pull/277
We've to update workflow when it's merged
=> Workflow check extrinsic order

node/service/src/instant_finalize.rs, node/service/src/lib.rs
this will cause double finalize warning, not sure if there is a better way
=> instant finalize mandala dev blocks

node/cli/src/command.rs, node/service/src/chain_spec/mod.rs
issue: https://github.com/AcalaNetwork/Acala/issues/1575
use dummy chain spec to get chain spec id from jsonn file
=> chain spec

runtime/acala/src/lib.rs, runtime/integration-tests/src/homa_lite.rs, runtime/integration-tests/src/setup.rs, runtime/karura/src/lib.rs, runtime/mandala/src/lib.rs
Updated integration tests accordingly.
=> Increase the minimum mint and redeem for HomaLite

runtime/acala/src/lib.rs, runtime/common/Cargo.toml, runtime/common/src/precompile/dex.rs, runtime/common/src/precompile/mock.rs, runtime/common/src/precompile/mod.rs, runtime/common/src/precompile/multicurrency.rs, runtime/common/src/precompile/nft.rs, runtime/common/src/precompile/oracle.rs, runtime/common/src/precompile/schedule_call.rs, runtime/common/src/precompile/state_rent.rs, runtime/common/src/precompile/tests.rs, runtime/karura/src/lib.rs, runtime/mandala/src/lib.rs
closes https://github.com/AcalaNetwork/Acala/issues/736
`ScheduleCallPrecompile` needs special attention as it deals with `Call, Origin, PalletsOrigin` trait Bounds.
=> refactor AllPrecompiles

node/cli/src/command.rs, node/service/src/chain_spec/acala.rs, node/service/src/chain_spec/karura.rs, node/service/src/chain_spec/mandala.rs, node/service/src/chain_spec/mod.rs
=> block bad block

.devcontainer/Dockerfile, Makefile, README.md, scripts/Dockerfile
Updated build script.
Updated readme
Closes #1618
=> Added a new optimized build config for building release binary.

primitives/src/currency.rs, primitives/src/lib.rs, runtime/integration-tests/src/dex.rs
=> Support LiquidCroadloan and ForeignAsset for TradingPair

modules/transaction-payment/src/lib.rs, modules/transaction-payment/src/tests.rs, runtime/acala/src/constants.rs, runtime/karura/src/constants.rs, runtime/mandala/src/constants.rs, runtime/mandala/src/lib.rs
=> Refund extra tip

launch/config.yml, launch/package.json, launch/yarn.lock, node/cli/src/cli.rs
=> Remove parachain-id and update launch

modules/evm/src/lib.rs, modules/evm/src/mock.rs, node/service/src/chain_spec/mandala.rs, runtime/common/src/precompile/mock.rs, runtime/integration-tests/src/setup.rs
=> genesis evm dev account

modules/asset-registry/src/lib.rs, modules/asset-registry/src/mock.rs, modules/asset-registry/src/tests.rs, runtime/acala/src/lib.rs, runtime/common/src/precompile/mock.rs, runtime/karura/src/lib.rs, runtime/mandala/src/lib.rs
=> Add LiquidCroadloanCurrencyId for asset-registry

ecosystem-modules/ren/renvm-bridge/src/lib.rs, ecosystem-modules/ren/renvm-bridge/src/mock.rs, ecosystem-modules/starport/src/lib.rs, ecosystem-modules/starport/src/mock.rs, modules/cdp-treasury/src/lib.rs, modules/staking-pool/src/lib.rs, modules/staking-pool/src/mock.rs, runtime/integration-tests/src/setup.rs, runtime/mandala/src/benchmarking/homa.rs
`GenesisBuild` can be used in its place less verbose
=> Remove uneeded GenesisConfig implementation

runtime/mandala/src/lib.rs
=> mandala-patch

runtime/mandala/src/lib.rs
=> stable-asset-id

runtime/mandala/src/lib.rs
Reverts AcalaNetwork/Acala#1742
=> Revert "simulate-exchange-rate"

node/service/src/chain_spec/mandala.rs
Initialize DOT, AUSD in genesis
Closes: #1781
=> Add erc20 token for evm account

Cargo.lock, node/service/src/lib.rs, rpc/Cargo.toml, rpc/src/lib.rs
--instant-sealing will enable manual sealing as well, engine rpc for creating and finalizing blocks will be exposed
=> Manual sealing (Engine create/finalize RPC)

modules/evm/src/lib.rs, modules/evm/src/mock.rs, modules/evm/src/tests.rs, runtime/common/src/precompile/multicurrency.rs, runtime/common/src/precompile/schedule_call.rs, runtime/common/src/precompile/tests.rs
=> Use reducible_balance for evm balance

modules/transaction-payment/src/lib.rs, modules/transaction-payment/src/tests.rs, runtime/acala/src/lib.rs, runtime/integration-tests/src/evm.rs, runtime/integration-tests/src/payment.rs, runtime/integration-tests/src/setup.rs, runtime/karura/src/lib.rs, runtime/mandala/src/benchmarking/auction_manager.rs, runtime/mandala/src/benchmarking/cdp_engine.rs, runtime/mandala/src/benchmarking/dex.rs, runtime/mandala/src/benchmarking/dex_oracle.rs, runtime/mandala/src/benchmarking/homa.rs, runtime/mandala/src/benchmarking/honzon.rs, runtime/mandala/src/benchmarking/transaction_payment.rs, runtime/mandala/src/lib.rs
1. Enable integration tests for `mandala` and `acala` runtime
2. Modify `UpdateOrigin`
3. Fix `set_alternative_fee_swap_path`
4. Fix `enable_charge_fee_pool`
=> Fix transaction payment

runtime/acala/src/lib.rs, runtime/integration-tests/src/honzon.rs, runtime/karura/src/lib.rs
Increase MinimumDebitValue from 20 to 50 for Acala and Karura
=> Increase MinimumDebitValue

runtime/integration-tests/Cargo.toml
=> update feature flags

modules/evm/src/lib.rs, modules/support/src/lib.rs, runtime/acala/src/lib.rs, runtime/common/src/lib.rs, runtime/common/src/precompile/dex.rs, runtime/common/src/precompile/evm.rs, runtime/common/src/precompile/mock.rs, runtime/common/src/precompile/mod.rs, runtime/common/src/precompile/schedule.rs, runtime/common/src/precompile/tests.rs, runtime/karura/src/lib.rs, runtime/mandala/src/lib.rs
https://github.com/AcalaNetwork/predeploy-contracts/pull/79
=> Rename StateRent to EVM

modules/dex/src/lib.rs, modules/dex/src/tests.rs
=> check swap path

runtime/acala/src/lib.rs, runtime/karura/src/lib.rs, runtime/mandala/src/lib.rs
after v0.9.16 is upgraded, rm the on-runtime-upgrade
=> rm on-runtime-upgrade

.github/workflows/test.yml, Makefile, scripts/Dockerfile
closes: https://github.com/AcalaNetwork/Acala/issues/1716
fixes(?): https://github.com/AcalaNetwork/Acala/issues/1878
=> exclude integration-tests

runtime/acala/src/lib.rs, runtime/common/src/lib.rs, runtime/karura/src/lib.rs, runtime/mandala/src/lib.rs
=> add DexLiquidity Proxy

Makefile, modules/asset-registry/src/mock.rs, modules/currencies/src/mock.rs, modules/evm-bridge/src/mock.rs, modules/evm/src/lib.rs, modules/evm/src/runner/stack.rs, modules/support/src/dex.rs, modules/support/src/evm.rs, modules/support/src/honzon.rs, modules/support/src/lib.rs, primitives/src/evm.rs, primitives/src/lib.rs, runtime/common/src/mock.rs, runtime/common/src/precompile/mock.rs, runtime/integration-tests/src/evm.rs
Split big files into smaller ones
=> Minor refactor

modules/nominees-election/src/lib.rs, modules/nominees-election/src/tests.rs, primitives/src/bonding.rs, primitives/src/lib.rs
abstract bonding logic so it can be reused by other pallets later
=> Abstract bonding logic

modules/nominees-election/src/lib.rs, modules/nominees-election/src/mock.rs, modules/nominees-election/src/tests.rs, primitives/src/bonding/controller.rs, primitives/src/bonding/error.rs, primitives/src/bonding/ledger.rs, primitives/src/bonding/mod.rs, runtime/mandala/src/benchmarking/nominees_election.rs, runtime/mandala/src/lib.rs
refactor more bonding related logic into BondingController
=> BondingController

modules/auction-manager/src/mock.rs, modules/cdp-engine/src/mock.rs, modules/cdp-treasury/src/mock.rs, modules/dex/src/lib.rs, modules/dex/src/mock.rs, modules/dex/src/tests.rs, modules/dex/src/weights.rs, modules/transaction-payment/src/mock.rs, runtime/acala/src/lib.rs, runtime/acala/src/weights/module_dex.rs, runtime/common/src/precompile/mock.rs, runtime/karura/src/lib.rs, runtime/karura/src/weights/module_dex.rs, runtime/mandala/src/benchmarking/dex.rs, runtime/mandala/src/lib.rs, runtime/mandala/src/weights/module_dex.rs
=> allow to abort provisioning when do not meet target and expired

modules/asset-registry/src/mock.rs, modules/currencies/src/mock.rs, modules/evm-bridge/src/mock.rs, modules/evm/src/lib.rs, modules/evm/src/tests.rs, runtime/common/src/precompile/tests.rs, runtime/integration-tests/src/evm.rs, runtime/mandala/src/benchmarking/evm.rs
It is helpful for bodhi.js to get `used_gas`
=> Add used_gas and used_storage

runtime/karura/src/lib.rs
=> rm migration

.gitignore, Cargo.lock, modules/auction-manager/src/mock.rs, modules/cdp-engine/src/mock.rs, modules/cdp-treasury/src/mock.rs, modules/dex/Cargo.toml, modules/dex/src/lib.rs, modules/dex/src/mock.rs, modules/dex/src/tests.rs, modules/support/src/dex.rs, modules/support/src/mocks.rs, modules/transaction-payment/src/mock.rs, runtime/acala/src/lib.rs, runtime/common/src/precompile/mock.rs, runtime/karura/src/lib.rs, runtime/mandala/src/lib.rs
=> dex-aggregator

runtime/acala/src/lib.rs, runtime/karura/src/lib.rs, runtime/mandala/src/lib.rs
sp_api::MAX_EXTRINSIC_DEPTH is 256.
=> use decode_all_with_depth_limit instead of decode

ecosystem-modules/starport/src/mock.rs, modules/currencies/src/lib.rs, modules/currencies/src/mock.rs, modules/currencies/src/tests.rs, modules/homa-lite/src/mock.rs, modules/homa-lite/src/mock_no_fees.rs, modules/homa/src/mock.rs, modules/honzon-bridge/src/mock.rs, modules/nft/src/mock.rs, modules/transaction-payment/src/mock.rs, runtime/acala/src/lib.rs, runtime/common/src/precompile/mock.rs, runtime/karura/src/lib.rs, runtime/mandala/src/lib.rs
=> currencies transfer erc20 will charge gas

modules/cdp-engine/src/lib.rs, modules/cdp-engine/src/mock.rs, modules/cdp-engine/src/tests.rs, modules/honzon/src/mock.rs, runtime/acala/src/lib.rs, runtime/common/src/lib.rs, runtime/integration-tests/src/honzon.rs, runtime/karura/src/lib.rs, runtime/mandala/src/benchmarking/cdp_engine.rs, runtime/mandala/src/benchmarking/honzon.rs, runtime/mandala/src/lib.rs
Added new Config for cdp-engine : minimum collateral amount
Added new unit tests
Configured the collateral amount to be 100x ED in runtimes
Closes #1956
=> Added minimal collateral amount for cdp-engine module

modules/cdp-engine/src/lib.rs, modules/cdp-engine/src/tests.rs, runtime/integration-tests/src/honzon.rs
Fix a bug where user cannot withdraws all debit and collateral i debit is 0.
Now minimum collateral amount is only maintained if user does not withdraw all of its collaterals
=> Fix a bug where user cannot withdraw all CDP collaterals

scripts/Dockerfile
Closes: #2114 
https://github.com/AcalaNetwork/Acala/actions/runs/2323203404
=> Update to phusion/baseimage:focal-1.2.0

Cargo.lock, runtime/mandala/Cargo.toml, runtime/mandala/src/lib.rs
Changelog:
- Adds orml-payments to mandala runtime
=> add orml-payments to mandala runtime

modules/asset-registry/src/mock.rs, modules/currencies/src/mock.rs, modules/evm-accounts/src/lib.rs, modules/evm-bridge/src/mock.rs, modules/evm/src/bench/mock.rs, modules/evm/src/lib.rs, modules/evm/src/mock.rs, modules/evm/src/runner/stack.rs, modules/support/src/evm.rs, node/service/src/chain_spec/acala.rs, node/service/src/chain_spec/karura.rs, node/service/src/chain_spec/mandala.rs, runtime/acala/src/lib.rs, runtime/common/src/mock.rs, runtime/common/src/precompile/mock.rs, runtime/integration-tests/src/setup.rs, runtime/karura/src/lib.rs, runtime/mandala/src/lib.rs, ts-tests/package.json, ts-tests/tests/test-precompiles.ts, ts-tests/tests/test-sign-eip1559.ts, ts-tests/tests/test-sign-eip712.ts, ts-tests/tests/test-sign-eth.ts, ts-tests/yarn.lock
=> Add testnet chainId

rpc/src/lib.rs
=> Added a new RPC call for dev: get block stats

modules/cdp-engine/src/lib.rs
Closes: #2129 
I'll add more tests.
=> Fix cdp-engine offchain worker

modules/evm-accounts/src/lib.rs, modules/support/src/evm.rs, runtime/common/src/precompile/evm_accounts.rs, runtime/integration-tests/src/evm.rs
https://github.com/AcalaNetwork/predeploy-contracts/pull/101
=> Add claimDefaultEvmAddress

runtime/common/src/precompile/dex.rs, runtime/common/src/precompile/evm_accounts.rs, runtime/common/src/precompile/multicurrency.rs, runtime/common/src/precompile/schedule.rs, runtime/common/src/precompile/stable_asset.rs
The contract query interface, if the data does not exist, return the default value
=> Return default value instead of error

runtime/acala/src/xcm_config.rs, runtime/karura/src/xcm_config.rs, runtime/mandala/src/xcm_config.rs
=> Add ERC20 token cross-chain transfer support.

modules/homa/src/lib.rs, modules/homa/src/migrations/mod.rs, modules/homa/src/migrations/v1.rs, modules/homa/src/tests.rs, runtime/acala/src/lib.rs, runtime/common/src/precompile/homa.rs, runtime/karura/src/lib.rs, runtime/mandala/src/lib.rs
=> Add Total Staking to Homa Storage

modules/honzon/src/lib.rs, modules/support/src/honzon.rs, runtime/common/src/precompile/honzon.rs
=> Add Debit Exchange Rate to precompile

modules/emergency-shutdown/src/lib.rs, modules/honzon/src/lib.rs
closes #2184
This is a breaking change to API
=> CollateralCurrencyIds is no longer a constant

primitives/src/currency.rs
https://github.com/AcalaNetwork/predeploy-contracts/pull/108
=> add predeploy-contracts tokens

modules/transaction-payment/src/lib.rs, modules/transaction-payment/src/tests.rs
closes: https://github.com/AcalaNetwork/Acala/issues/2204
=> Add TransactionFeePaid event

runtime/karura/src/lib.rs
Closes: #1967
https://blockscout.karura.network/token/0xE20683ad1ED8bbeED7E1aE74Be10F19D8045B530/token-transfers
=> Enable honzon-bridge

.github/workflows/publish-release.yml
New tag is available now, no need to point to master
=> Update srtool-action tag

launch/config.yml, launch/karura-bifrost.yml
Update so people can try new predeploys
=> Update Launch Docker Images

runtime/integration-tests/src/relaychain/statemine.rs
Reverts AcalaNetwork/Acala#2242
=> Revert "Revert "Companion orml#786""

modules/asset-registry/src/lib.rs, runtime/acala/src/xcm_config.rs, runtime/integration-tests/src/relaychain/kusama_cross_chain_transfer.rs, runtime/karura/src/xcm_config.rs, runtime/mandala/src/xcm_config.rs
closes: https://github.com/AcalaNetwork/Acala/issues/2260
=> Support stable asset xtokens transfer

Makefile
=> Added benchmark-machine make command

runtime/acala/src/weights/nutsfinance_stable_asset.rs, runtime/karura/src/weights/nutsfinance_stable_asset.rs, runtime/mandala/src/benchmarking/nutsfinance_stable_asset.rs, runtime/mandala/src/weights/nutsfinance_stable_asset.rs
add capabilities to modify fees
=> stable-asset-fees

primitives/src/currency.rs
https://github.com/AcalaNetwork/predeploy-contracts/pull/121
=> Update karura & acala tokens

modules/evm/src/lib.rs, modules/evm/src/tests.rs
=> fix developer check

modules/honzon/Cargo.toml, modules/honzon/src/lib.rs, modules/support/src/honzon.rs, runtime/common/src/precompile/honzon.rs
closes #2298
Note this will be breaking change to honzon predeploy
=> Honzon Precompile to output all collateral parameters

Cargo.lock, node/service/src/chain_spec/acala.rs, node/service/src/chain_spec/karura.rs, node/service/src/chain_spec/mandala.rs, primitives/src/evm.rs, runtime/acala/src/lib.rs, runtime/common/Cargo.toml, runtime/common/src/lib.rs, runtime/integration-tests/src/runtime.rs, runtime/integration-tests/src/setup.rs, runtime/karura/src/lib.rs, runtime/mandala/src/lib.rs
=> Skip checking relay chain block numbers on testnet

runtime/common/src/precompile/incentives.rs
https://github.com/AcalaNetwork/predeploy-contracts/pull/131
=> Remove GetDexRewardRate

.github/workflows/build-release.yml, .github/workflows/docker-build.yml
https://github.com/AcalaNetwork/Acala/actions/runs/3171454886/jobs/5164920515
https://github.com/AcalaNetwork/Acala/blob/b1b8c744654f23bb2a39c43e403c2592c4f381f5/Makefile#L51-L72
build-mandala-release work with `PROFILE=production`
build-mandala-internal-release work with `PROFILE=release`
=> Fix docker build images

node/cli/src/command.rs, node/service/src/chain_spec/acala.rs, node/service/src/chain_spec/karura.rs
=> Add acala-local and karura-local chain id

runtime/mandala/src/benchmarking/nutsfinance_stable_asset.rs, runtime/mandala/src/benchmarking/utils.rs
modify benchmarks according to audit
=> stable-asset-benchmarks

runtime/acala/src/xcm_config.rs, runtime/integration-tests/src/relaychain/kusama_cross_chain_transfer.rs, runtime/integration-tests/src/relaychain/polkadot_cross_chain_transfer.rs, runtime/karura/src/xcm_config.rs
Replace #2393 as there is no access to update the origin PR
=> Update send XCM origin

runtime/mandala/src/benchmarking/nutsfinance_stable_asset.rs
=> stable-asset-bench

.github/workflows/benchmark.yml
=> use nodejs 16

.github/workflows/build-release.yml
https://github.com/AcalaNetwork/Acala/actions/runs/3616075681/jobs/6093693117
=> Fix build images

.github/workflows/build-release.yml, .github/workflows/docker-build.yml, scripts/Dockerfile
Test action: https://github.com/AcalaNetwork/Acala/actions/runs/3616352492
=> fix docker build

modules/evm/src/lib.rs, modules/evm/src/runner/stack.rs, modules/evm/src/runner/state.rs
=> Add CustomStackState trait

.github/workflows/docker-build-internal.yml, .github/workflows/docker-build-production.yml, .github/workflows/docker-build-profiling.yml
https://github.com/AcalaNetwork/Acala/actions/runs/4538529443
=> Update workflow to upgrade node.js

Cargo.lock, runtime/common/src/precompile/xtokens.rs
=> use xtokens weight

runtime/acala/src/lib.rs, runtime/integration-tests/src/stable_asset.rs, runtime/karura/src/lib.rs, runtime/mandala/src/lib.rs
Fix bugs in stable asset balance conversion logic
=> Fix bugs in stable asset balance conversion logic

Cargo.lock, modules/evm/src/lib.rs, node/e2e-tests/test-service/src/builder.rs, node/service/src/lib.rs, runtime/integration-tests/Cargo.toml, runtime/integration-tests/src/relaychain/kusama_cross_chain_transfer.rs, runtime/integration-tests/src/relaychain/mod.rs, runtime/integration-tests/src/relaychain/polkadot_cross_chain_transfer.rs, runtime/integration-tests/src/relaychain/relay_chain.rs, runtime/integration-tests/src/relaychain/statemine.rs, runtime/integration-tests/src/relaychain/statemint.rs, runtime/integration-tests/src/xcm_interface.rs
It's weird that staking_unbond failed because execute the xcm message occurs `XcmError::MaxWeightInvalid`,  
though the weight limit  should be sane. I try to set huge weight_limit and fee,  but it is still the same mistake.
=> Fix some integration tests

primitives/src/evm.rs, primitives/src/tests.rs
https://github.com/AcalaNetwork/bodhi.js/pull/740
=> fix decode_gas_limit

README.md, modules/evm-accounts/src/lib.rs
=> Fix: typos

modules/transaction-payment/src/lib.rs, modules/transaction-payment/src/tests.rs, modules/transaction-payment/src/weights.rs, primitives/src/unchecked_extrinsic.rs, runtime/acala/src/lib.rs, runtime/acala/src/weights/module_transaction_payment.rs, runtime/karura/src/lib.rs, runtime/karura/src/weights/module_transaction_payment.rs, runtime/mandala/src/benchmarking/transaction_payment.rs, runtime/mandala/src/lib.rs, runtime/mandala/src/weights/module_transaction_payment.rs
Current implementation is unsafe and too complicated to do it safely
=> remove with_fee_paid_by

node/cli/src/command.rs
fixed `--rpc-external` for relaychain have no effect issue
=> fix relaychain rpc external

.github/workflows/coverage.yml, .github/workflows/test.yml, .github/workflows/test.yml.src
=> use concurrency

scripts/verify-bootnodes.sh
dev is removed from relaychain
=> fix verify bootnodes

Cargo.lock, modules/dex/src/lib.rs, modules/transaction-payment/src/lib.rs, runtime/acala/src/xcm_config.rs, runtime/karura/src/xcm_config.rs, runtime/mandala/src/xcm_config.rs, rust-toolchain.toml
- Upgrade rust 1.75.0
- Upgrade `staging-xcm-builder` and `staging-xcm-executor` to v7.0.3
=> Upgrade rust 1.75.0

modules/asset-registry/src/mock.rs, modules/currencies/src/mock.rs, modules/evm-bridge/src/mock.rs, modules/evm/src/bench/mod.rs, modules/evm/src/lib.rs, modules/evm/src/mock.rs, modules/evm/src/runner/stack.rs, modules/evm/src/runner/state.rs, modules/evm/src/tests.rs, modules/honzon-bridge/src/mock.rs, modules/support/src/evm.rs, runtime/common/src/precompile/evm.rs, runtime/integration-tests/src/evm.rs, runtime/integration-tests/src/honzon.rs, runtime/integration-tests/src/stable_asset.rs, runtime/mandala/src/benchmarking/asset_registry.rs, runtime/mandala/src/benchmarking/evm.rs
=> only make contract unpublished when deployer is in developer mode

modules/honzon/src/lib.rs, modules/xcm-interface/src/lib.rs, runtime/mandala/src/lib.rs
=> chore: fix typos

ts-tests/package.json, ts-tests/yarn.lock
use latest bodhi to avoid importing evmchai
=> use latest bodhi

runtime/karura/src/lib.rs
will include this into 2260 runtime
=> allow signed migration

Cargo.lock, runtime/acala/Cargo.toml, runtime/acala/src/lib.rs, runtime/karura/src/lib.rs
=> remove pallet_state_trie_migration

README.md
=> fix-Update README.md

modules/assethub/src/lib.rs
=> confirm the assethub pallet index
